# Generated by Django 4.2.1 on 2023-05-06 16:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ActiveSubstance",
            fields=[
                (
                    "name",
                    models.CharField(
                        max_length=2000, primary_key=True, serialize=False
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Price",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("official_trade_price", models.FloatField()),
                ("indication_range", models.CharField(max_length=2000)),
                ("off_label_indication_range", models.CharField(max_length=2000)),
                ("payment_level", models.CharField(max_length=2000)),
                ("beneficiary_surcharge", models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name="Medicine",
            fields=[
                (
                    "GTIN_number",
                    models.CharField(
                        max_length=2000, primary_key=True, serialize=False
                    ),
                ),
                ("sheet_nr", models.CharField(max_length=5)),
                ("name", models.CharField(max_length=2000)),
                ("form", models.CharField(max_length=2000)),
                ("dose", models.CharField(max_length=2000)),
                ("package_contents", models.CharField(max_length=2000)),
                (
                    "active_substance",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="med_browser.activesubstance",
                    ),
                ),
                (
                    "price",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="med_browser.price",
                    ),
                ),
            ],
        ),
    ]
