# Generated by Django 4.2.1 on 2023-05-13 13:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("med_browser", "0002_medicine_id_alter_medicine_gtin_number"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="medicine",
            name="price",
        ),
        migrations.AddField(
            model_name="price",
            name="medicine",
            field=models.ForeignKey(
                default=0,
                on_delete=django.db.models.deletion.CASCADE,
                to="med_browser.medicine",
            ),
            preserve_default=False,
        ),
    ]
